name: C CI

on:
  push:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        lz4: [no, v1.9.3]

    steps:
    - name: check kernel version
      run: uname -a
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install uuid-dev libfuse-dev
    - name: install lz4
      if: ${{ matrix.lz4 != 'no' }}
      run: |
        cd
        git clone --depth=1 --branch=${{ matrix.lz4 }} https://github.com/lz4/lz4.git
        cd lz4
        make
        sudo make install
        sudo ldconfig
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-fuse
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make check (fuse)
      run: FSTYP=erofsfuse make check
    - name: make check (root)
      run: sudo make check
    - uses: actions/upload-artifact@v2
      if: ${{ !cancelled() }}
      with:
        name: test-results-lz4-${{ matrix.lz4 }}
        path: tests/results
    - name: make distcheck
      run: make distcheck
